basePath: /
definitions:
  server.CreateUrlRequest:
    properties:
      redirectUrl:
        type: string
    required:
      - redirectUrl
    type: object
  server.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  server.UrlDTO:
    properties:
      redirectUrl:
        type: string
      urlId:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go + Gin API
  version: "1.0"
paths:
  /ping:
    get:
      description: Ping the server
      operationId: ping
      produces:
        - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"
      summary: Ping the server
      tags:
        - ping
  /url:
    post:
      description: Create a new url
      operationId: create-url
      parameters:
        - description: url
          in: body
          name: url
          required: true
          schema:
            $ref: "#/definitions/server.CreateUrlRequest"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/server.UrlDTO"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"
      summary: Create a new url
      tags:
        - url
  /url/{urlId}:
    get:
      description: Get the redirect url
      operationId: get-url
      parameters:
        - description: url id
          in: path
          name: urlId
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/server.UrlDTO"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/server.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/server.ErrorResponse"
      summary: Get the redirect url
      tags:
        - url
schemes:
  - http
securityDefinitions:
  JWT_AUTH:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
