// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: src/proto/pkg/urlspb/urlspb.proto

package urlspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId       string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
	RedirectUrl string `protobuf:"bytes,2,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

func (x *Url) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type GetUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
}

func (x *GetUrlRequest) Reset() {
	*x = GetUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlRequest) ProtoMessage() {}

func (x *GetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUrlRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{1}
}

func (x *GetUrlRequest) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

type GetUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url *Url `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetUrlResponse) Reset() {
	*x = GetUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlResponse) ProtoMessage() {}

func (x *GetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUrlResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{2}
}

func (x *GetUrlResponse) GetUrl() *Url {
	if x != nil {
		return x.Url
	}
	return nil
}

type CreateUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUrl string `protobuf:"bytes,1,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
}

func (x *CreateUrlRequest) Reset() {
	*x = CreateUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlRequest) ProtoMessage() {}

func (x *CreateUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateUrlRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUrlRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type CreateUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
}

func (x *CreateUrlResponse) Reset() {
	*x = CreateUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlResponse) ProtoMessage() {}

func (x *CreateUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateUrlResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUrlResponse) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

type UpdateUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url *Url `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UpdateUrlRequest) Reset() {
	*x = UpdateUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUrlRequest) ProtoMessage() {}

func (x *UpdateUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUrlRequest.ProtoReflect.Descriptor instead.
func (*UpdateUrlRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUrlRequest) GetUrl() *Url {
	if x != nil {
		return x.Url
	}
	return nil
}

type DeleteUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
}

func (x *DeleteUrlRequest) Reset() {
	*x = DeleteUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlRequest) ProtoMessage() {}

func (x *DeleteUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlRequest.ProtoReflect.Descriptor instead.
func (*DeleteUrlRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUrlRequest) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

type NoContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoContent) Reset() {
	*x = NoContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoContent) ProtoMessage() {}

func (x *NoContent) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoContent.ProtoReflect.Descriptor instead.
func (*NoContent) Descriptor() ([]byte, []int) {
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP(), []int{7}
}

var File_src_proto_pkg_urlspb_urlspb_proto protoreflect.FileDescriptor

var file_src_proto_pkg_urlspb_urlspb_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x03, 0x55,
	0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x25, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75,
	0x72, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49,
	0x64, 0x22, 0x2f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x34, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x29, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72,
	0x6c, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x55, 0x72,
	0x6c, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72,
	0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64,
	0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0xfc, 0x01,
	0x0a, 0x0b, 0x55, 0x72, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x15, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x18, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x18, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x75, 0x72, 0x6c, 0x73,
	0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x31, 0x0a, 0x06,
	0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x42, 0x06, 0x55, 0x72, 0x6c, 0x73, 0x50, 0x62, 0x50, 0x01,
	0x5a, 0x1d, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_pkg_urlspb_urlspb_proto_rawDescOnce sync.Once
	file_src_proto_pkg_urlspb_urlspb_proto_rawDescData = file_src_proto_pkg_urlspb_urlspb_proto_rawDesc
)

func file_src_proto_pkg_urlspb_urlspb_proto_rawDescGZIP() []byte {
	file_src_proto_pkg_urlspb_urlspb_proto_rawDescOnce.Do(func() {
		file_src_proto_pkg_urlspb_urlspb_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_pkg_urlspb_urlspb_proto_rawDescData)
	})
	return file_src_proto_pkg_urlspb_urlspb_proto_rawDescData
}

var file_src_proto_pkg_urlspb_urlspb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_src_proto_pkg_urlspb_urlspb_proto_goTypes = []interface{}{
	(*Url)(nil),               // 0: urlspb.Url
	(*GetUrlRequest)(nil),     // 1: urlspb.GetUrlRequest
	(*GetUrlResponse)(nil),    // 2: urlspb.GetUrlResponse
	(*CreateUrlRequest)(nil),  // 3: urlspb.CreateUrlRequest
	(*CreateUrlResponse)(nil), // 4: urlspb.CreateUrlResponse
	(*UpdateUrlRequest)(nil),  // 5: urlspb.UpdateUrlRequest
	(*DeleteUrlRequest)(nil),  // 6: urlspb.DeleteUrlRequest
	(*NoContent)(nil),         // 7: urlspb.NoContent
}
var file_src_proto_pkg_urlspb_urlspb_proto_depIdxs = []int32{
	0, // 0: urlspb.GetUrlResponse.url:type_name -> urlspb.Url
	0, // 1: urlspb.UpdateUrlRequest.url:type_name -> urlspb.Url
	1, // 2: urlspb.UrlsService.GetUrl:input_type -> urlspb.GetUrlRequest
	3, // 3: urlspb.UrlsService.CreateUrl:input_type -> urlspb.CreateUrlRequest
	5, // 4: urlspb.UrlsService.UpdateUrl:input_type -> urlspb.UpdateUrlRequest
	6, // 5: urlspb.UrlsService.DeleteUrl:input_type -> urlspb.DeleteUrlRequest
	2, // 6: urlspb.UrlsService.GetUrl:output_type -> urlspb.GetUrlResponse
	4, // 7: urlspb.UrlsService.CreateUrl:output_type -> urlspb.CreateUrlResponse
	7, // 8: urlspb.UrlsService.UpdateUrl:output_type -> urlspb.NoContent
	7, // 9: urlspb.UrlsService.DeleteUrl:output_type -> urlspb.NoContent
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_proto_pkg_urlspb_urlspb_proto_init() }
func file_src_proto_pkg_urlspb_urlspb_proto_init() {
	if File_src_proto_pkg_urlspb_urlspb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_pkg_urlspb_urlspb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_pkg_urlspb_urlspb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_pkg_urlspb_urlspb_proto_goTypes,
		DependencyIndexes: file_src_proto_pkg_urlspb_urlspb_proto_depIdxs,
		MessageInfos:      file_src_proto_pkg_urlspb_urlspb_proto_msgTypes,
	}.Build()
	File_src_proto_pkg_urlspb_urlspb_proto = out.File
	file_src_proto_pkg_urlspb_urlspb_proto_rawDesc = nil
	file_src_proto_pkg_urlspb_urlspb_proto_goTypes = nil
	file_src_proto_pkg_urlspb_urlspb_proto_depIdxs = nil
}
