// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: pkg/proto/urlspb/urlspb.proto

package urlspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	apipb "urlshortener/pkg/proto/apipb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
}

func (x *GetUrlRequest) Reset() {
	*x = GetUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlRequest) ProtoMessage() {}

func (x *GetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_urlspb_urlspb_proto_rawDescGZIP(), []int{0}
}

func (x *GetUrlRequest) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

type CreateUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUrl string `protobuf:"bytes,1,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
}

func (x *CreateUrlRequest) Reset() {
	*x = CreateUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlRequest) ProtoMessage() {}

func (x *CreateUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_urlspb_urlspb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUrlRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type UpdateUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId       string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
	RedirectUrl string `protobuf:"bytes,2,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
}

func (x *UpdateUrlRequest) Reset() {
	*x = UpdateUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUrlRequest) ProtoMessage() {}

func (x *UpdateUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUrlRequest.ProtoReflect.Descriptor instead.
func (*UpdateUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_urlspb_urlspb_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUrlRequest) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

func (x *UpdateUrlRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type DeleteUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
}

func (x *DeleteUrlRequest) Reset() {
	*x = DeleteUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlRequest) ProtoMessage() {}

func (x *DeleteUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlRequest.ProtoReflect.Descriptor instead.
func (*DeleteUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_urlspb_urlspb_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUrlRequest) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

type GetUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId       string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
	RedirectUrl string `protobuf:"bytes,2,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
}

func (x *GetUrlResponse) Reset() {
	*x = GetUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlResponse) ProtoMessage() {}

func (x *GetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUrlResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_urlspb_urlspb_proto_rawDescGZIP(), []int{4}
}

func (x *GetUrlResponse) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

func (x *GetUrlResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type CreateUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
}

func (x *CreateUrlResponse) Reset() {
	*x = CreateUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlResponse) ProtoMessage() {}

func (x *CreateUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_urlspb_urlspb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateUrlResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_urlspb_urlspb_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUrlResponse) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

var File_pkg_proto_urlspb_urlspb_proto protoreflect.FileDescriptor

var file_pkg_proto_urlspb_urlspb_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x73,
	0x70, 0x62, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x1a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72,
	0x6c, 0x22, 0x4a, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x28, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72, 0x6c,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72,
	0x6c, 0x22, 0x29, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x32, 0xa4, 0x02, 0x0a,
	0x04, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x37, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x12,
	0x15, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x2e, 0x75, 0x72,
	0x6c, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x37, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x2e,
	0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e,
	0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x70, 0x62, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72,
	0x6c, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_urlspb_urlspb_proto_rawDescOnce sync.Once
	file_pkg_proto_urlspb_urlspb_proto_rawDescData = file_pkg_proto_urlspb_urlspb_proto_rawDesc
)

func file_pkg_proto_urlspb_urlspb_proto_rawDescGZIP() []byte {
	file_pkg_proto_urlspb_urlspb_proto_rawDescOnce.Do(func() {
		file_pkg_proto_urlspb_urlspb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_urlspb_urlspb_proto_rawDescData)
	})
	return file_pkg_proto_urlspb_urlspb_proto_rawDescData
}

var file_pkg_proto_urlspb_urlspb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_urlspb_urlspb_proto_goTypes = []interface{}{
	(*GetUrlRequest)(nil),      // 0: urlspb.GetUrlRequest
	(*CreateUrlRequest)(nil),   // 1: urlspb.CreateUrlRequest
	(*UpdateUrlRequest)(nil),   // 2: urlspb.UpdateUrlRequest
	(*DeleteUrlRequest)(nil),   // 3: urlspb.DeleteUrlRequest
	(*GetUrlResponse)(nil),     // 4: urlspb.GetUrlResponse
	(*CreateUrlResponse)(nil),  // 5: urlspb.CreateUrlResponse
	(*apipb.PingRequest)(nil),  // 6: apipb.PingRequest
	(*apipb.NoContent)(nil),    // 7: apipb.NoContent
	(*apipb.PingResponse)(nil), // 8: apipb.PingResponse
}
var file_pkg_proto_urlspb_urlspb_proto_depIdxs = []int32{
	0, // 0: urlspb.Urls.GetUrl:input_type -> urlspb.GetUrlRequest
	1, // 1: urlspb.Urls.CreateUrl:input_type -> urlspb.CreateUrlRequest
	2, // 2: urlspb.Urls.UpdateUrl:input_type -> urlspb.UpdateUrlRequest
	3, // 3: urlspb.Urls.DeleteUrl:input_type -> urlspb.DeleteUrlRequest
	6, // 4: urlspb.Urls.Ping:input_type -> apipb.PingRequest
	4, // 5: urlspb.Urls.GetUrl:output_type -> urlspb.GetUrlResponse
	5, // 6: urlspb.Urls.CreateUrl:output_type -> urlspb.CreateUrlResponse
	7, // 7: urlspb.Urls.UpdateUrl:output_type -> apipb.NoContent
	7, // 8: urlspb.Urls.DeleteUrl:output_type -> apipb.NoContent
	8, // 9: urlspb.Urls.Ping:output_type -> apipb.PingResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_urlspb_urlspb_proto_init() }
func file_pkg_proto_urlspb_urlspb_proto_init() {
	if File_pkg_proto_urlspb_urlspb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_urlspb_urlspb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_urlspb_urlspb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_urlspb_urlspb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_urlspb_urlspb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_urlspb_urlspb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_urlspb_urlspb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_urlspb_urlspb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_urlspb_urlspb_proto_goTypes,
		DependencyIndexes: file_pkg_proto_urlspb_urlspb_proto_depIdxs,
		MessageInfos:      file_pkg_proto_urlspb_urlspb_proto_msgTypes,
	}.Build()
	File_pkg_proto_urlspb_urlspb_proto = out.File
	file_pkg_proto_urlspb_urlspb_proto_rawDesc = nil
	file_pkg_proto_urlspb_urlspb_proto_goTypes = nil
	file_pkg_proto_urlspb_urlspb_proto_depIdxs = nil
}
