// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import ()

type Url struct {
	UrlID       string `db:"url_id" json:"url_id"`
	RedirectUrl string `db:"redirect_url" json:"redirect_url"`
}
