// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: pkg/proto/cachepb/cachepb.proto

package cachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	urlspb "urlshortener/pkg/proto/urlspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=urlId,proto3" json:"urlId,omitempty"`
}

func (x *GetUrlRequest) Reset() {
	*x = GetUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlRequest) ProtoMessage() {}

func (x *GetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cachepb_cachepb_proto_rawDescGZIP(), []int{0}
}

func (x *GetUrlRequest) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

type GetUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUrl string `protobuf:"bytes,1,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
}

func (x *GetUrlResponse) Reset() {
	*x = GetUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlResponse) ProtoMessage() {}

func (x *GetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUrlResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cachepb_cachepb_proto_rawDescGZIP(), []int{1}
}

func (x *GetUrlResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type SetUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url *urlspb.Url `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SetUrlRequest) Reset() {
	*x = SetUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUrlRequest) ProtoMessage() {}

func (x *SetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUrlRequest.ProtoReflect.Descriptor instead.
func (*SetUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cachepb_cachepb_proto_rawDescGZIP(), []int{2}
}

func (x *SetUrlRequest) GetUrl() *urlspb.Url {
	if x != nil {
		return x.Url
	}
	return nil
}

type NoContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoContent) Reset() {
	*x = NoContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoContent) ProtoMessage() {}

func (x *NoContent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cachepb_cachepb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoContent.ProtoReflect.Descriptor instead.
func (*NoContent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cachepb_cachepb_proto_rawDescGZIP(), []int{3}
}

var File_pkg_proto_cachepb_cachepb_proto protoreflect.FileDescriptor

var file_pkg_proto_cachepb_cachepb_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62, 0x1a, 0x1d, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2f, 0x75, 0x72, 0x6c,
	0x73, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x72,
	0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64,
	0x22, 0x32, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x55, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x32, 0x7f, 0x0a, 0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x39, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x2e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06,
	0x53, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x42, 0x20, 0x5a, 0x1e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_cachepb_cachepb_proto_rawDescOnce sync.Once
	file_pkg_proto_cachepb_cachepb_proto_rawDescData = file_pkg_proto_cachepb_cachepb_proto_rawDesc
)

func file_pkg_proto_cachepb_cachepb_proto_rawDescGZIP() []byte {
	file_pkg_proto_cachepb_cachepb_proto_rawDescOnce.Do(func() {
		file_pkg_proto_cachepb_cachepb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_cachepb_cachepb_proto_rawDescData)
	})
	return file_pkg_proto_cachepb_cachepb_proto_rawDescData
}

var file_pkg_proto_cachepb_cachepb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_cachepb_cachepb_proto_goTypes = []interface{}{
	(*GetUrlRequest)(nil),  // 0: cachepb.GetUrlRequest
	(*GetUrlResponse)(nil), // 1: cachepb.GetUrlResponse
	(*SetUrlRequest)(nil),  // 2: cachepb.SetUrlRequest
	(*NoContent)(nil),      // 3: cachepb.NoContent
	(*urlspb.Url)(nil),     // 4: urlspb.Url
}
var file_pkg_proto_cachepb_cachepb_proto_depIdxs = []int32{
	4, // 0: cachepb.SetUrlRequest.url:type_name -> urlspb.Url
	0, // 1: cachepb.CacheService.GetUrl:input_type -> cachepb.GetUrlRequest
	2, // 2: cachepb.CacheService.SetUrl:input_type -> cachepb.SetUrlRequest
	1, // 3: cachepb.CacheService.GetUrl:output_type -> cachepb.GetUrlResponse
	3, // 4: cachepb.CacheService.SetUrl:output_type -> cachepb.NoContent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_cachepb_cachepb_proto_init() }
func file_pkg_proto_cachepb_cachepb_proto_init() {
	if File_pkg_proto_cachepb_cachepb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_cachepb_cachepb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_cachepb_cachepb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_cachepb_cachepb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_cachepb_cachepb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_cachepb_cachepb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_cachepb_cachepb_proto_goTypes,
		DependencyIndexes: file_pkg_proto_cachepb_cachepb_proto_depIdxs,
		MessageInfos:      file_pkg_proto_cachepb_cachepb_proto_msgTypes,
	}.Build()
	File_pkg_proto_cachepb_cachepb_proto = out.File
	file_pkg_proto_cachepb_cachepb_proto_rawDesc = nil
	file_pkg_proto_cachepb_cachepb_proto_goTypes = nil
	file_pkg_proto_cachepb_cachepb_proto_depIdxs = nil
}
