apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: cmg/api-svc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: API_SVC_PORT
              value: "8080"
            - name: API_SVC_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: api-svc-name
            - name: API_SVC_URL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: api-svc-url
            - name: API_SVC_CACHE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: api-svc-cache-timeout
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-svc-url
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-db
            - name: URL_SVC_ADDR
              valueFrom:
                configMapKeyRef:
                  name: url-config
                  key: url-svc-url
            - name: URL_SVC_NAME
              valueFrom:
                configMapKeyRef:
                  name: url-config
                  key: url-svc-name

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
