apiVersion: v1
kind: Service
metadata:
  namespace: urlshortener
  name: urlshortener
spec:
  type: ClusterIP
  selector:
    app: urlshortener
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
    - name: http
      protocol: TCP
      port: 8080
