apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: urlshortener
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: cmg/web-svc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: WEB_SVC_PORT
              value: "8080"
            - name: WEB_SVC_URL
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: web-svc-url
            - name: WEB_SVC_CACHE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: web-svc-cache-timeout
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-svc-url
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-db
            - name: URL_SVC_ADDR
              valueFrom:
                configMapKeyRef:
                  name: url-config
                  key: url-svc-url

---
apiVersion: v1
kind: Service
metadata:
  namespace: urlshortener
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
