version: "3.9"

services:  
  api_service:
    container_name: api_service
    depends_on:
      - urls_service
      - redis_cache
    build:
      context: ../src/api_service
    env_file:
      - .env
    ports:
      - "${API_SVC_PORT}:${API_SVC_PORT}"

  urls_service:
    container_name: urls_service
    # depends_on:
    #   - postgres_db
    build:
      context: ../src/urls_service
    env_file:
      - .env
    ports:
      - "${URLS_SVC_PORT}:${URLS_SVC_PORT}"

  redis_cache:
    container_name: redis_cache
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
      
volumes:
  redis_data:
   