version: "3.9"

services:
    websvc:
        container_name: websvc
        depends_on:
            - urlsvc
            - redis_cache
        build:
            context: ../cmd/websvc
        env_file:
            - .env
        ports:
            - "${WEB_SVC_PORT}:${WEB_SVC_PORT}"

    urlsvc:
        container_name: urlsvc
        build:
            context: ../cmd/urlsvc
        env_file:
            - .env
        ports:
            - "${URL_SVC_PORT}:${URL_SVC_PORT}"

    redis_cache:
        container_name: redis_cache
        image: redis
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
