// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: src/cache_service/pkg/cache/proto/urlspb/urlspb.proto

package urlspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UrlsServiceClient is the client API for UrlsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlsServiceClient interface {
	GetUrl(ctx context.Context, in *GetUrlRequest, opts ...grpc.CallOption) (*GetUrlResponse, error)
	CreateUrl(ctx context.Context, in *CreateUrlRequest, opts ...grpc.CallOption) (*CreateUrlResponse, error)
	UpdateUrl(ctx context.Context, in *UpdateUrlRequest, opts ...grpc.CallOption) (*NoContent, error)
	DeleteUrl(ctx context.Context, in *DeleteUrlRequest, opts ...grpc.CallOption) (*NoContent, error)
}

type urlsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlsServiceClient(cc grpc.ClientConnInterface) UrlsServiceClient {
	return &urlsServiceClient{cc}
}

func (c *urlsServiceClient) GetUrl(ctx context.Context, in *GetUrlRequest, opts ...grpc.CallOption) (*GetUrlResponse, error) {
	out := new(GetUrlResponse)
	err := c.cc.Invoke(ctx, "/urlspb.UrlsService/GetUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlsServiceClient) CreateUrl(ctx context.Context, in *CreateUrlRequest, opts ...grpc.CallOption) (*CreateUrlResponse, error) {
	out := new(CreateUrlResponse)
	err := c.cc.Invoke(ctx, "/urlspb.UrlsService/CreateUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlsServiceClient) UpdateUrl(ctx context.Context, in *UpdateUrlRequest, opts ...grpc.CallOption) (*NoContent, error) {
	out := new(NoContent)
	err := c.cc.Invoke(ctx, "/urlspb.UrlsService/UpdateUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlsServiceClient) DeleteUrl(ctx context.Context, in *DeleteUrlRequest, opts ...grpc.CallOption) (*NoContent, error) {
	out := new(NoContent)
	err := c.cc.Invoke(ctx, "/urlspb.UrlsService/DeleteUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlsServiceServer is the server API for UrlsService service.
// All implementations must embed UnimplementedUrlsServiceServer
// for forward compatibility
type UrlsServiceServer interface {
	GetUrl(context.Context, *GetUrlRequest) (*GetUrlResponse, error)
	CreateUrl(context.Context, *CreateUrlRequest) (*CreateUrlResponse, error)
	UpdateUrl(context.Context, *UpdateUrlRequest) (*NoContent, error)
	DeleteUrl(context.Context, *DeleteUrlRequest) (*NoContent, error)
	mustEmbedUnimplementedUrlsServiceServer()
}

// UnimplementedUrlsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUrlsServiceServer struct {
}

func (UnimplementedUrlsServiceServer) GetUrl(context.Context, *GetUrlRequest) (*GetUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUrl not implemented")
}
func (UnimplementedUrlsServiceServer) CreateUrl(context.Context, *CreateUrlRequest) (*CreateUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUrl not implemented")
}
func (UnimplementedUrlsServiceServer) UpdateUrl(context.Context, *UpdateUrlRequest) (*NoContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUrl not implemented")
}
func (UnimplementedUrlsServiceServer) DeleteUrl(context.Context, *DeleteUrlRequest) (*NoContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUrl not implemented")
}
func (UnimplementedUrlsServiceServer) mustEmbedUnimplementedUrlsServiceServer() {}

// UnsafeUrlsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlsServiceServer will
// result in compilation errors.
type UnsafeUrlsServiceServer interface {
	mustEmbedUnimplementedUrlsServiceServer()
}

func RegisterUrlsServiceServer(s grpc.ServiceRegistrar, srv UrlsServiceServer) {
	s.RegisterService(&UrlsService_ServiceDesc, srv)
}

func _UrlsService_GetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlsServiceServer).GetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlspb.UrlsService/GetUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlsServiceServer).GetUrl(ctx, req.(*GetUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlsService_CreateUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlsServiceServer).CreateUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlspb.UrlsService/CreateUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlsServiceServer).CreateUrl(ctx, req.(*CreateUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlsService_UpdateUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlsServiceServer).UpdateUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlspb.UrlsService/UpdateUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlsServiceServer).UpdateUrl(ctx, req.(*UpdateUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlsService_DeleteUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlsServiceServer).DeleteUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlspb.UrlsService/DeleteUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlsServiceServer).DeleteUrl(ctx, req.(*DeleteUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlsService_ServiceDesc is the grpc.ServiceDesc for UrlsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urlspb.UrlsService",
	HandlerType: (*UrlsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUrl",
			Handler:    _UrlsService_GetUrl_Handler,
		},
		{
			MethodName: "CreateUrl",
			Handler:    _UrlsService_CreateUrl_Handler,
		},
		{
			MethodName: "UpdateUrl",
			Handler:    _UrlsService_UpdateUrl_Handler,
		},
		{
			MethodName: "DeleteUrl",
			Handler:    _UrlsService_DeleteUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/cache_service/pkg/cache/proto/urlspb/urlspb.proto",
}
