basePath: /
definitions:
  web_service.CreateUrlRequest:
    properties:
      redirectUrl:
        type: string
    required:
    - redirectUrl
    type: object
  web_service.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  web_service.UrlDto:
    properties:
      newUrl:
        type: string
      redirectUrl:
        type: string
      urlId:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a URL shortener service.
  title: URL Shortener API
  version: "1.0"
paths:
  /{urlId}:
    get:
      description: Redirect to url
      operationId: redirect-url
      parameters:
      - description: url id
        in: path
        name: urlId
        required: true
        type: string
      responses:
        "302":
          description: Found
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web_service.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web_service.ErrorResponse'
      summary: Redirect to url
      tags:
      - url
  /ping:
    get:
      description: Ping the server
      operationId: ping
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web_service.ErrorResponse'
      summary: Ping the server
      tags:
      - ping
  /url:
    post:
      description: Create a new url redirect
      operationId: create-url
      parameters:
      - description: url
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/web_service.CreateUrlRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web_service.UrlDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web_service.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web_service.ErrorResponse'
      summary: Create a new url redirect
      tags:
      - url
  /url/{urlId}:
    get:
      description: Get url
      operationId: get-url
      parameters:
      - description: url id
        in: path
        name: urlId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web_service.UrlDto'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web_service.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web_service.ErrorResponse'
      summary: Get url
      tags:
      - url
schemes:
- http
swagger: "2.0"
